CREATE TABLE fact_respondents (
    respondent_id               SERIAL      PRIMARY KEY,
    age_group                   VARCHAR(10),
    email                       VARCHAR(100),
    gender                      SMALLINT    CHECK (gender BETWEEN 1 AND 3),
    education_level             VARCHAR(35),
    occupation                  SMALLINT    CHECK (occupation BETWEEN 1 AND 5),
    monthly_income              VARCHAR(30),
    area_of_residence           VARCHAR(25),
    class_label                 VARCHAR(20),
    shopping_frequency          SMALLINT    CHECK (shopping_frequency BETWEEN 1 AND 4),
    product_preference          SMALLINT    CHECK (product_preference BETWEEN 1 AND 4),
    clothes_preference          SMALLINT    CHECK (clothes_preference BETWEEN 1 AND 4),
    grocery_preference          SMALLINT    CHECK (grocery_preference BETWEEN 1 AND 4),
    electronics_preference      SMALLINT    CHECK (electronics_preference BETWEEN 1 AND 4),
    branded_quality             SMALLINT    CHECK (branded_quality BETWEEN 1 AND 5),
    unbranded_vfm               SMALLINT    CHECK (unbranded_vfm BETWEEN 1 AND 5),
    branded_social_status       SMALLINT    CHECK (branded_social_status BETWEEN 1 AND 4),
    brand_confidence            SMALLINT    CHECK (brand_confidence BETWEEN 1 AND 5),
    mumbai_brand_influence      SMALLINT    CHECK (mumbai_brand_influence BETWEEN 1 AND 5),
    social_media_influence      SMALLINT    CHECK (social_media_influence BETWEEN 1 AND 5),
    local_market_influence      SMALLINT    CHECK (local_market_influence BETWEEN 1 AND 5),
    mall_influence              SMALLINT    CHECK (mall_influence BETWEEN 1 AND 5),
    price_consciousness         SMALLINT    CHECK (price_consciousness BETWEEN 1 AND 5),
    buying_behaviour            SMALLINT    CHECK (buying_behaviour BETWEEN 1 AND 4),
    cat_clothing                SMALLINT    CHECK (cat_clothing BETWEEN 0 AND 1),
    cat_electronics             SMALLINT    CHECK (cat_electronics BETWEEN 0 AND 1),
    cat_footwear                SMALLINT    CHECK (cat_footwear BETWEEN 0 AND 1),
    cat_groceries               SMALLINT    CHECK (cat_groceries BETWEEN 0 AND 1),
    cat_personal_care_products  SMALLINT    CHECK (cat_personal_care_products BETWEEN 0 AND 1),
    factor_advertisement        SMALLINT    CHECK (factor_advertisement BETWEEN 0 AND 1),
    factor_brand_name           SMALLINT    CHECK (factor_brand_name BETWEEN 0 AND 1),
    factor_price                SMALLINT    CHECK (factor_price BETWEEN 0 AND 1),
    factor_quality              SMALLINT    CHECK (factor_quality BETWEEN 0 AND 1),
    factor_recommendations_from_others SMALLINT CHECK (factor_recommendations_from_others BETWEEN 0 AND 1),
    factor_social_status        SMALLINT    CHECK (factor_social_status BETWEEN 0 AND 1)
);